In [1]:
%timeit [j**4 for j in range(1,9)]

552 ns ± 49.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
import numpy as np 
%timeit np.arange(1,9)**4

In [ ]:
import numpy as np 
l=[]
for i in range(1,5):
        l.append(int(input("enter : ")))
print(np.array(l))
# l=[]
# for i in range(1,5):
#     for j in range(1,5):
#         l.append(int(input("enter : ")))
#     l.append(" ")
# print(np.array(l))

In [ ]:
import numpy as np 
l=[[1,2,3,4],[1,2,3,4],[1,2,3,4]]
print(np.array(l))

In [ ]:
import numpy as np
l=[]
for i in range(1,4):
    l+=[[]]
    for j in range(1,4):
        l.append(int(input(f"enter : [{i}][{j}]")))
    
print(np.array(l))

In [ ]:
import numpy as np
l=[]
for i in range(1,3):
    l+=[[]]
    for j in range(1,4):
        l[-1]+=input(f"enter : [{i}][{j}]")
    
print(np.array(l))

In [4]:
# make a numpy array of only zeros
import numpy as np
ar_zero=np.zeros(5)
print(ar_zero)
print()
# ``multidimensional array of zeros``

ar_zero1=np.zeros((3,4))
print(ar_zero1)

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
import numpy as np
ar_ones=np.ones(5)

print(ar_ones)
# ``multidimensional array of ones``
print()
ar_zero1=np.ones((3,4))
print(ar_zero1)

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
# empty array of numpy
import numpy as np
ar_em=np.empty(3)
print(ar_em)

[1.32714377e-311 0.00000000e+000 4.94065646e-324]
